apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
spec:
  containers:
    - name: test-container
      image: ellerbrock/alpine-bash-curl-ssl
      command:
      - sleep
      - "3600"
      volumeMounts:
        # name must match the volume name below
        - name: curlrc
          mountPath: /home/download/.curlrc
          subPath: ".curlrc"
          readOnly: true
  # The secret data is exposed to Containers in the Pod through a Volume.
  volumes:
    - name: curlrc
      secret:
        secretName: curlrc